name: azkar
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+1

environment:
  sdk: ^3.8.1

dependencies:
  animated_text_kit: ^4.2.3
  audioplayers: ^6.5.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^17.2.3
  flutter_qiblah: ^3.1.0+1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  geocoding: ^4.0.0
  geolocator: ^13.0.4
  google_fonts: ^6.3.0
  hijri: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  intl: ^0.20.2
  jailbreak_root_detection: ^1.1.6
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.1
  quickalert: ^1.1.0
  rename: ^3.1.0
  retrofit: ^4.7.0
  shared_preferences: ^2.5.3
  table_calendar: ^3.2.0
  timezone: ^0.9.4
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/al-quran.png"

flutter_native_splash:
  color: "#040C23"
  image: assets/al-quran.png
  android: true
  ios: true
  android_12:
    color: "#040C23"
    # image: assets/al-quran.png

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
