-keep class okhttp3.** { *; }
-keep class retrofit2.** { *; }
-keep class com.google.gson.** { *; }
-dontwarn okhttp3.**
-dontwarn retrofit2.**
-dontwarn com.google.gson.**
-keep class com.powermoko.jailbreak_root_detection.** { *; }
-keep class io.flutter.embedding.engine.** { *; }
